[workspace]
members = ["starknet_scripts", "tests"]
default-members = ["starknet_scripts"]
resolver = "2"

[workspace.dependencies]
starknet = "0.4.0"

[patch."https://github.com/starkware-libs/blockifier"]
blockifier = { git = "https://github.com/dojoengine/blockifier", rev = "a31892d" }

[patch.crates-io]
cairo-felt = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "51a35b2b405f29786e48a94f364d64d373d79eea" }
cairo-vm = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "51a35b2b405f29786e48a94f364d64d373d79eea" }

cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-debug = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-diagnostics = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-formatter = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-lowering = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-plugins = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-project = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1", features = [ "testing" ] }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-sierra-ap-change = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-sierra-gas = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-sierra-generator = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-sierra-to-casm = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo.git", tag = "v2.0.1" }
