[package]
name = "renegade_contracts"
version = "0.1.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[tool.nile_rs]
artifacts_dir = "./target/release/"
contracts_dir = "./src"

[dependencies]
starknet = ">=2.0.2"
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria" }
