[package]
name = "contracts-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
num-bigint = { version = "0.4", default-features = false }

[dev-dependencies]
sha3 = { version = "^0.10", default-features = false }
jf-plonk = { git = "https://github.com/renegade-fi/mpc-jellyfish.git", features = [
    "test-srs",
    "test_apis",
] }
jf-primitives = { git = "https://github.com/renegade-fi/mpc-jellyfish.git", default-features = false }
jf-relation = { git = "https://github.com/renegade-fi/mpc-jellyfish.git", default-features = false }
jf-utils = { git = "https://github.com/renegade-fi/mpc-jellyfish.git" }
byteorder = "1.5"
