[package]
name = "contracts-core"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
alloy-primitives = { workspace = true }


[dev-dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-std = { workspace = true }
sha3 = { version = "^0.10", default-features = false }
jf-utils = { git = "https://github.com/renegade-fi/mpc-jellyfish.git" }
test-helpers = { path = "../test-helpers" }
rand = { workspace = true }
