[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
contracts-core = { path = "../contracts-core" }
test-helpers = { path = "../test-helpers" }
tokio = { version = "1.12.0", features = ["full"] }
ethers = "2.0"
eyre = "0.6.8"
ark-ff = { workspace = true }
ark-std = { workspace = true }
rand = "0.8.5"
clap = { version = "4.4.7", features = ["derive"] }
json = "0.12"
postcard = { workspace = true }
