[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
contracts-core = { path = "../contracts-core" }
test-helpers = { path = "../test-helpers" }
deploy-scripts = { path = "../deploy-scripts" }
tokio = { workspace = true }
ethers = { workspace = true }
eyre = { workspace = true }
ark-ff = { workspace = true }
ark-std = { workspace = true }
ark-ec = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }
json = "0.12"
postcard = { workspace = true }
serde = { workspace = true }
alloy-primitives = { workspace = true }
ark-crypto-primitives = { workspace = true }
