[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
contracts-common = { path = "../contracts-common" }
contracts-core = { path = "../contracts-core" }
contracts-utils = { path = "../contracts-utils" }
scripts = { path = "../scripts" }
tokio = { workspace = true }
ethers = { workspace = true }
eyre = { workspace = true }
ark-ff = { workspace = true }
ark-std = { workspace = true }
ark-ec = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
ark-crypto-primitives = { workspace = true }
circuit-types = { workspace = true, features = ["test-helpers"] }
circuits = { workspace = true }
constants = { workspace = true }
arbitrum-client = { workspace = true }
jf-primitives = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
inventory = "0.3"

test-helpers = { git = "https://github.com/renegade-fi/renegade.git", branch = "zksecurity-audit" }
colored = "2"
