[package]
name = "contracts-stylus"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = { version = "0.4.1" }
wee_alloc = "0.4.5"
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-bn254 = { workspace = true }
common = { path = "../common" }
contracts-core = { path = "../contracts-core" }
ark-std = { version = "0.4.0", optional = true }

[features]
darkpool = []
verifier = []
precompile-test-contract = ["dep:ark-std"]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]
