[package]
name = "contracts-stylus"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = { version = "0.4.2" }
wee_alloc = "0.4.5"
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-bn254 = { workspace = true }
common = { path = "../common" }
contracts-core = { path = "../contracts-core" }
postcard = { workspace = true }
alloy-sol-types = { workspace = true }

[features]
darkpool = []
darkpool-test-contract = []
no-verify = []
merkle = []
merkle-test-contract = []
verifier = []
verifier-test-contract = []
vkeys = []
test-vkeys = []
precompile-test-contract = []
dummy-erc20 = []
dummy-upgrade-target = []
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]
