name: Cairo Tests

on: pull_request

env:
  SCARB_ARCHIVE_LINK: https://github.com/software-mansion/scarb/releases/download/v0.5.0-alpha.0/scarb-v0.5.0-alpha.0-x86_64-unknown-linux-gnu.tar.gz

jobs:
  test_cairo:
    name: test_cairo
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Install Scarb
        uses: ./.github/actions/install_scarb
        with:
          SCARB_ARCHIVE_LINK: $SCARB_ARCHIVE_LINK

      - name: Run tests
        run: scarb test -- -f renegade_contracts
      